config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :borrowings
  resources :books
  resources :categories
  resources :available_books
  devise_for :users
  root 'home#index'
  get 'borrow', to: 'home#borrow'
  get 'reserve', to: 'home#reserve'
  resources :users, only: %i[index destroy]
end

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :borrowing_date, presence:true
  validates :due_date, presence:true
end

app/controllers/borrowings_controller.rb
class BorrowingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_borrowing, only: %i[show edit update destroy]

  # GET /borrowings or /borrowings.json
  def index
    @borrowings = Borrowing.all
  end

  # GET /borrowings/1 or /borrowings/1.json
  def show; end

  # GET /borrowings/new
  def new
    @borrowing = Borrowing.new
    @book = Book.find(params[:book_id])
  end

  def blog; end

  # GET /borrowings/1/edit
  def edit; end

  # POST /borrowings or /borrowings.json
  def create
    borrowing = Borrowing.new(borrowing_params)
    borrowing.user = current_user

    if Borrowing.where(book_id: borrowing.book_id, user_id: borrowing.user_id).exists?
      return redirect_to books_path, notice: 'Already Borrowed this book.'
    end

    if Borrowing.where(user_id: borrowing.user_id).count >= 3
      return redirect_to books_path, notice: ' Already Borrowed three books.'
    end

    return redirect_to books_path, notice: 'Borrowed the Book successifuly' if borrowing.save

    render('new', status: 422)
  end

  # PATCH/PUT /borrowings/1 or /borrowings/1.json
  def update
    respond_to do |format|
      if @borrowing.update(borrowing_params)
        format.html { redirect_to borrowings_path, notice: 'Updated your details successfully.' }
        format.json { render :show, status: :ok, location: @borrowing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @borrowing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrowings/1 or /borrowings/1.json
  def destroy
    @borrowing.destroy

    respond_to do |format|
      format.html { redirect_to borrowings_url, notice: 'Updated your details successfully' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_borrowing
    @borrowing = Borrowing.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def borrowing_params
    params.require(:borrowing).permit(:borrowing_date, :due_date, :user_id, :book_id)
  end
end

app/helpers/borrowings_helper.rb
module BorrowingsHelper
end

app/views/borrowings/_book.html.erb
<div class='flex id="<%= dom_id book %> '>
  <img class="h-4/5 book w-2/5" src="<%= book.image_url %>" alt="book">
  <div class='h-4/5 w-2/5 ml-4 flex flex-col justify-center'>
    <div>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite unlike"></i>
    </div>
    <h3 class='font-serif text-sm font-semibold mt-2'> <%= book.title %></h3>
    <h4 class='font-sans text-xs mt-2'> <%= book.author %></h4>
    <p class='font-sans text-xs mt-2 borrowed'>You reserved this book <i class="uil uil-shield-check text-base"></i></p>
    <div class='flex gap-3 mt-2'>
      <%= link_to 'Edit',edit_borrowing_path(id:borrowing.id), class:'button text-xs  p-1 rounded-lg' %>
      <%= button_to 'Return', borrowing_path(id: borrowing.id), method: :delete, class: 'button text-xs p-1 rounded-lg' %>
    </div>
  </div>
</div>

app/views/borrowings/_borrowing.html.erb
<div id="<%= dom_id borrowing %>">
  <p>
    <strong>Borrowing date:</strong>
    <%= borrowing.borrowing_date %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= borrowing.due_date %>
  </p>

  <p>
    <strong>User:</strong>
    <%= borrowing.user_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= borrowing.book_id %>
  </p>

</div>

app/views/borrowings/_editform.html.erb
<section class="bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
      <%= image_tag('book.png', class: 'h-8 w-8 mr-2', alt: 'logo') %>
      ShelfWise
    </a>
    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
          Edit Returning Date
        </h1>
        <%= form_with(model: borrowing, class: 'space-y-4 md:space-y-6') do |form| %>
          <%= form.label :Due_date, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= form.date_field :due_date, min: Date.current.to_s, class:'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', required: true %>
          <%= form.hidden_field :borrowing_date, value: Date.current.to_s, readonly: true %>
          <%= form.hidden_field :book_id, value: borrowing.book_id %>
          <%= form.submit "Save this changes",class:"w-full cursor-pointer mt-5 text-white bg-blue-700  hover:bg-blue-800  focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
        <%end %>
      </div>
    </div>
  </div>
</section>

app/views/borrowings/_form.html.erb
<section class="bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
      <%= image_tag('book.png', class: 'h-8 w-8 mr-2', alt: 'logo') %>
      ShelfWise
    </a>
    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
          Select Returning Date
        </h1>
        <%= form_with(model: borrowing, class: 'space-y-4 md:space-y-6') do |form| %>
          <%= form.label :Due_date, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
          <%= form.date_field :due_date, min: Date.current.to_s, class:'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', required: true %>
          <%= form.hidden_field :borrowing_date, value: Date.current.to_s, readonly: true %>
          <%= form.hidden_field :book_id, value: @book.id %>
          <%= form.submit "Borrow this Book",class:"w-full cursor-pointer mt-5 text-white bg-blue-700  hover:bg-blue-800  focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
        <%end %>
      </div>
    </div>
  </div>
</section>

app/views/borrowings/blog.html.erb
<h1>blog</h1>

app/views/borrowings/edit.html.erb
<%= render "editform", borrowing: @borrowing %>

app/views/borrowings/index.html.erb
<div class="flex items-center space-x-4">
  <div class="w-full">
    <h1 class='mt-6 text-center text-gray-700 font-serif mb-16 text-5xl  md:text-6xl xl:text-7xl'>My <br/>
      Borrowings</h1>
  </div>
</div>
<section class='flex justify-center p-5'>
  <div id="reservations" class=' container grid md:grid-cols-3 gap-4'>
    <% current_user.borrowings.each do |borrowing| %>
      <%= render 'book', book:borrowing.book,borrowing:borrowing %>
    <% end %>
  </div>
</section>
<% if current_user.borrowings.length === 0 %>
  <div class="flex justify-center p-4 mb-4 text-sm text-textColor rounded-lg bg-lightBg dark:bg-gray-800 dark:text-blue-400" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 mr-3 mt-[2px]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <div>
      <span class="font-medium">You have not Borrowed any book yet</span>
    </div>
  </div>
<% end %>

app/views/borrowings/new.html.erb
<%= render "form", borrowing: @borrowing %>

app/views/borrowings/show.html.erb
<%= render @borrowing %>
<div>
  <%= link_to "Edit this borrowing", edit_borrowing_path(@borrowing) %> |
  <%= link_to "Back to borrowings", borrowings_path %>
  <%= button_to "Destroy this borrowing", @borrowing, method: :delete %>
</div>