config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :borrowings
  resources :books
  resources :categories
  resources :available_books
  devise_for :users
  root 'home#index'
  get 'borrow', to: 'home#borrow'
  get 'reserve', to: 'home#reserve'
  resources :users, only: %i[index destroy]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :borrowings, dependent: :destroy
  has_many :reservations, dependent: :destroy

  validates :title, presence: true
  validates :author, presence: true
  validates :image_url, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: %i[show edit update destroy]

  # GET /books or /books.json
  def index
    @books = if params[:query].present?
               query = "%#{params[:query]}%"
               @books = Book.where('title ILIKE ? OR author ILIKE ?', query, query)
             else
               Book.all
             end

    if turbo_frame_request?
      render partial: 'books', locals: { books: @books }
    else
      render 'index'
    end
  end

  # GET /books/1 or /books/1.json
  def show
    authorize! :read, @book
  end

  # GET /books/new
  def new
    @book = Book.new
    authorize! :create, @book
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    authorize! :update, @book
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Created the book  successfully .' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_path, notice: ' updated the Book successfully .' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    authorize! :destroy, @book
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_path, notice: 'destroyed. this Book successfully ' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :image_url, :category_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class='flex id="<%= dom_id book %> '>
  <img class="h-4/5 book w-2/5" src="<%= book.image_url %>" alt="book">
  <div class='h-4/5 w-2/5 ml-4 flex flex-col justify-center'>
    <div>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite unlike"></i>
    </div>
    <h3 class='font-serif text-sm font-semibold mt-2'> <%= book.title %></h3>
    <h4 class='font-sans text-xs mt-2'> <%= book.author %></h4>
    <%if current_user.admin? %>
      <%= link_to "view", book,  data: { turbo_frame: "_top" }, class:"text-textColor mt-3   shadow-lg dark:shadow-lg  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button" %>
    <% else %>
      <% if book.borrowings.exists? && book.reservations.exists? %>
        <% if book.reservations.exists?(user_id: current_user.id) %>
          <p class='font-sans text-xs mt-2 borrowed'>You reserved this book <i class="uil uil-shield-check text-base"></i></p>
        <% elsif book.borrowings.exists?(user_id: current_user.id) %>
          <p class='font-sans text-xs mt-2 borrowed'>You borrowed this book <i class="uil uil-shield-check text-base"></i></p>
        <% else %>
          <p class='font-sans text-xs mt-2 borrowed'>This book is not available <i class="uil uil-exclamation-octagon text-base"></i></p>
        <% end %>
      <% elsif book.borrowings.exists? %>
        <% if book.borrowings.exists?(user_id: current_user.id) %>
          <p class='font-sans text-xs mt-2 borrowed'>You borrowed this book  <i class="uil uil-shield-check text-base"></i></p>
        <% else %>
          <%= link_to "Reserve", new_reservation_path(book_id: book.id),  data: { turbo_frame: "_top" }, class:"text-textColor mt-3   shadow-lg dark:shadow-lg  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button" %>
        <% end %>
      <% else %>
        <%= link_to new_borrowing_path(book_id: book.id), class: "text-textColor mt-3 shadow-lg dark:shadow-lg font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button",
            data: { turbo_frame: "_top" } do %>
          Borrow
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/books/_books.html.erb
<%= turbo_frame_tag "books" do %>
  <div class=" container  pl-5 grid md:grid-cols-3 gap-4">
    <% @books.each do |book| %>
      <%= render 'book', book:book %>
    <% end %>
  </div>
  <% if @books.length === 0 %>
    <div class="flex p-4 mb-4 text-sm text-textColor rounded-lg bg-lightBg dark:bg-gray-800 dark:text-blue-400" role="alert">
      <svg class="flex-shrink-0 inline w-4 h-4 mr-3 mt-[2px]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
      </svg>
      <span class="sr-only">Info</span>
      <div>
        <span class="font-medium">The Book is not found, you can:</span>
        <ul class="mt-1.5 ml-4 list-disc list-inside">
          <div class='flex gap-1 items-center'>
            <i class="uil uil-check"></i>
            <li>Try using different keywords</li>
          </div>
          <div class='flex gap-1 items-center'>
            <i class="uil uil-check"></i>
            <li>Check the spelling</li>
          </div>
          <div class='flex gap-1 items-center'>
            <i class="uil uil-check"></i>
            <li>Explore Categories</li>
          </div>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>

app/views/books/_editform.html.erb
<section class="bg-gray-50 dark:bg-gray-900 mt-5">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
      <%= image_tag('book.png', class: 'h-8 w-8 mr-2', alt: 'logo') %>
      ShelfWise
    </a>
    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
          Edit this book
        </h1>
        <%= form_with(model: book,class: 'space-y-4 md:space-y-6') do |f| %>
          <div>
            <%= f.label :Title, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.text_field :title, autofocus: true, autocomplete: "email", class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', required:true %>
          </div>
          <div class='mt-5'>
            <%= f.label :Author, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.text_field :author,  autocomplete: 'current-password', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500',required:true %>
          </div>
          <div class='mt-5'>
            <%= f.label :Image_Url, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.text_field :image_url,  autocomplete: 'current-password', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500',required:true %>
          </div>
          <div class='mt-5'>
            <%= f.label :Category, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.select :category_id, Category.all.map { |category| [category.name, category.id] }, { required: true }, class: 'block border-gray-300  w-full p-2.5 mt-2 bg-white border rounded-lg shadow-sm focus:outline-none focus:ring focus:border-blue-300' %>
          </div>
          <div class='mt-5'>
            <%= f.submit "Edit this book", class:"w-full cursor-pointer mt-5 text-white bg-blue-700  hover:bg-blue-800  focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title,required: true %>
  </div>
  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author, required: true %>
  </div>
  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url,required: true %>
  </div>
  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, Category.all.map { |category| [category.name, category.id] } %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%= render "editform", book: @book %>

app/views/books/index.html.erb
<!-- Section: Design Block -->
<section class="mb-40 bg-lightBg">
  <div class="px-6 py-12 text-center md:px-12 lg:text-left">
    <div class="w-100 mx-auto sm:max-w-2xl md:max-w-3xl lg:max-w-5xl xl:max-w-7xl xl:px-32">
      <div class="grid items-center lg:grid-cols-2">
        <div class="mb-12 md:mt-12 lg:mt-0 lg:mb-0">
          <div
            class="block rounded-lg bg-[hsla(0,0%,100%,0.55)] px-6 py-12 shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] dark:bg-[hsla(0,0%,5%,0.55)] dark:shadow-black/20 md:px-12 lg:-mr-14 backdrop-blur-[30px]">
            <h1 class="mt-2 mb-16 text-4xl  tracking-tight md:text-5xl xl:text-6xl font-serif text-textColor">
              New & <br />
              <span class="text-primary">Trending</span>
            </h1>
            <%= link_to 'My books' , borrowings_path, class:"mb-2 inline-block rounded bg-primary px-12 pt-4 pb-3.5 text-sm font-medium uppercase leading-normal text-textColor shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] dark:shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] dark:hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] dark:focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] dark:active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] md:mr-2 md:mb-0" %>
            <%= link_to 'My Reservations' , reservations_path, class:"inline-block rounded px-12 pt-4 pb-3.5 text-sm font-medium uppercase leading-normal text-primary transition duration-150  ease-in-out hover:bg-neutral-500 hover:bg-opacity-10 hover:text-primary-600 focus:text-primary-600 focus:outline-none focus:ring-0 active:text-primary-700 dark:hover:bg-neutral-700 dark:hover:bg-opacity-40" %>
          </div>
        </div>
        <div class="md:mb-12 lg:mb-0">
          <img src="https://img.freepik.com/free-vector/abstract-elegant-winter-book-cover_23-2148798745.jpg?size=626&ext=jpg"
            class="w-full  shadow-lg dark:shadow-black/20" alt="" />
        </div>
      </div>
    </div>
  </div>
</section>
<section class='flex flex-col justify-center  items-center'>
  <% if current_user.admin? %>
    <%= link_to "Create a New Book", new_book_path, class:"text-textColor mb-11 shadow-lg dark:shadow-lg  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button" %>
  <% end %>
  <%= form_with(url: books_path, method: "GET", class: 'pb-20 w-1/2 flex justify-center' , data: { controller: "form-submission", turbo_frame: "books", turbo_action: "advance" }) do |form| %>
    <div class='flex w-full items-center gap-2 justify-center'>
      <%= form.text_field :query, placeholder: "Search Titles, Author", data: { action: "input->form-submission#search" }, class: ' border-bodyColor bg-transparent md:w-1/2 text-textColor text-sm input rounded-full font-sans input py-2.5 px-8' %>
      <i class="uil uil-search text-2xl cursor-pointer unlike "></i>
    </div>
  <% end %>
  <%= render 'books' %>
</section>

app/views/books/new.html.erb
<%= render "form", book: @book %>

app/views/books/show.html.erb
<section class='flex justify-center items-center h-screen'>
  <div class=" max-w-sm mt-10 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <div>
      <img class="p-8 rounded-t-lg" src="<%= @book.image_url %>" alt="product image" />
    </div>
    <div class="px-5 pb-5">
      <div>
        <h3 class='font-serif text-sm font-semibold mt-2'> <%= @book.title %></h3>
        <h4 class='font-sans text-xs mt-2'> <%= @book.author %></h4>
      </div>
      <div class="flex items-center mt-2.5 mb-5">
        <i class="uil uil-favorite like"></i>
        <i class="uil uil-favorite like"></i>
        <i class="uil uil-favorite like"></i>
        <i class="uil uil-favorite like"></i>
        <i class="uil uil-favorite unlike"></i>
      </div>
      <div class="flex items-center justify-between">
        <%= link_to "Edit this book", edit_book_path(@book),class:"text-white button focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
        <%= button_to "Destroy this book", book_path(@book), data: { confirm: "Are you sure?" }, method: :delete, class:"text-white button focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      </div>
    </div>
  </section>