config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :borrowings
  resources :books
  resources :categories
  resources :available_books
  devise_for :users
  root 'home#index'
  get 'borrow', to: 'home#borrow'
  get 'reserve', to: 'home#reserve'
  resources :users, only: %i[index destroy]
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books, dependent: :destroy

    validates :name, presence:true
    validates :image_url, presence:true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_user!

  before_action :set_category, only: %i[show edit update destroy]



  # GET /categories or /categories.json

  def index

    @categories = Category.all

  end



  # GET /categories/1 or /categories/1.json

  def show

    @category = Category.find(params[:id])

    @books = @category.books

  end



  # GET /categories/new

  def new

    @category = Category.new

    authorize! :create, @category

  end



  # GET /categories/1/edit

  def edit

    @category = Category.find(params[:id])

    authorize! :update, @category

  end



  # POST /categories or /categories.json

  def create

    @category = Category.new(category_params)



    respond_to do |format|

      if @category.save

        format.html { redirect_to categories_path, notice: 'created the Category successfully' }

        format.json { render :show, status: :created, location: @category }

      else

        format.html { render :new, status: :unprocessable_entity }

        format.json { render json: @category.errors, status: :unprocessable_entity }

      end

    end

  end



  # PATCH/PUT /categories/1 or /categories/1.json

  def update

    respond_to do |format|

      if @category.update(category_params)

        format.html { redirect_to category_url(@category), notice: 'updated the Category successfully .' }

        format.json { render :show, status: :ok, location: @category }

      else

        format.html { render :edit, status: :unprocessable_entity }

        format.json { render json: @category.errors, status: :unprocessable_entity }

      end

    end

  end



  # DELETE /categories/1 or /categories/1.json

  def destroy

    @category.destroy



    respond_to do |format|

      format.html { redirect_to categories_url, notice: 'destroyed the Category  successfully .' }

      format.json { head :no_content }

    end

  end



  private



  # Use callbacks to share common setup or constraints between actions.

  def set_category

    @category = Category.find(params[:id])

  end



  # Only allow a list of trusted parameters through.

  def category_params

    params.require(:category).permit(:name, :image_url)

  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_book.html.erb
<div class='flex id="<%= dom_id book %> '>
  <img class="h-4/5 book w-2/5" src="<%= book.image_url %>" alt="book">
  <div class='h-4/5 w-2/5 ml-4 flex flex-col justify-center'>
    <div>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite like"></i>
      <i class="uil uil-favorite unlike"></i>
    </div>
    <h3 class='font-serif text-sm font-semibold mt-2'> <%= book.title %></h3>
    <h4 class='font-sans text-xs mt-2'> <%= book.author %></h4>
    <%if current_user.admin? %>
      <%= link_to "view", book,  data: { turbo_frame: "_top" }, class:"text-textColor mt-3   shadow-lg dark:shadow-lg  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button" %>
    <% else %>
      <% if book.borrowings.exists? && book.reservations.exists? %>
        <% if book.reservations.exists?(user_id: current_user.id) %>
          <p class='font-sans text-xs mt-2 borrowed'>You reserved this book <i class="uil uil-shield-check text-base"></i></p>
        <% elsif book.borrowings.exists?(user_id: current_user.id) %>
          <p class='font-sans text-xs mt-2 borrowed'>You borrowed this book <i class="uil uil-shield-check text-base"></i></p>
        <% else %>
          <p class='font-sans text-xs mt-2 borrowed'>This book is not available <i class="uil uil-exclamation-octagon text-base"></i></p>
        <% end %>
      <% elsif book.borrowings.exists? %>
        <% if book.borrowings.exists?(user_id: current_user.id) %>
          <p class='font-sans text-xs mt-2 borrowed'>You borrowed this book  <i class="uil uil-shield-check text-base"></i></p>
        <% else %>
          <%= link_to "Reserve", new_reservation_path(book_id: book.id),  data: { turbo_frame: "_top" }, class:"text-textColor mt-3   shadow-lg dark:shadow-lg  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button" %>
        <% end %>
      <% else %>
        <%= link_to new_borrowing_path(book_id: book.id), class: "text-textColor mt-3 shadow-lg dark:shadow-lg font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button",
            data: { turbo_frame: "_top" } do %>
          Borrow
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/categories/_category.html.erb
<div class="max-w-sm bg-white border border-gray-200  shadow dark:bg-gray-800 dark:border-gray-700">
  <img class="img w-full" src="<%= category.image_url %>" alt="" />
  <div class="p-5">
    <a href="#">
      <h5 class="mb-2 font-serif text-2xl font-bold tracking-tight text-textColor dark:text-white"><%= category.name %></h5>
    </a>
    <div class="inline-flex rounded-lg items-center px-3 py-2 text-sm font-medium text-center text-white button  focus:outline-none">
      <%= link_to "visit", category %>
      <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
      </svg>
    </div>
  </div>
</div>

app/views/categories/_editform.html.erb
<section class="bg-gray-50 dark:bg-gray-900 mt-5">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
      <%= image_tag('book.png', class: 'h-8 w-8 mr-2', alt: 'logo') %>
      ShelfWise
    </a>
    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
          Edit this  category
        </h1>
        <%= form_with(model: category,class: 'space-y-4 md:space-y-6') do |f| %>
          <div>
            <%= f.label :Name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.text_field :name, autofocus: true, autocomplete: "email", class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', required:true %>
          </div>
          <div class='mt-5'>
            <%= f.label :Image_Url, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.text_field :image_url,  autocomplete: 'current-password', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500',required:true %>
          </div>
          <div class='mt-5'>
            <%= f.submit "Edit this category", class:"w-full cursor-pointer mt-5 text-white bg-blue-700  hover:bg-blue-800  focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/categories/_form.html.erb
<section class="bg-gray-50 dark:bg-gray-900 mt-5">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
      <%= image_tag('book.png', class: 'h-8 w-8 mr-2', alt: 'logo') %>
      ShelfWise
    </a>
    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
          Create a category
        </h1>
        <%= form_with(model: category,class: 'space-y-4 md:space-y-6') do |f| %>
          <div>
            <%= f.label :Name, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.text_field :name, autofocus: true, autocomplete: "email", class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', required:true %>
          </div>
          <div class='mt-5'>
            <%= f.label :Image_Url, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
            <%= f.text_field :image_url,  autocomplete: 'current-password', class: 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500',required:true %>
          </div>
          <div class='mt-5'>
            <%= f.submit "Create a category", class:"w-full cursor-pointer mt-5 text-white bg-blue-700  hover:bg-blue-800  focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/categories/edit.html.erb
<%= render "editform", category: @category %>

app/views/categories/index.html.erb
<section class=' flex flex-col items-center justify-center px-4'>
  <h1 class='mt-6 text-center text-gray-700 font-serif mb-16 text-5xl  md:text-6xl xl:text-7xl'>Available <br/>
    categories</h1>
  <% if current_user.admin? %>
    <%= link_to "Create a New Category", new_category_path, class:"text-textColor mb-11 shadow-lg dark:shadow-lg  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button" %>
  <% end %>
  <div id="categories" class='container grid md:grid-cols-3 gap-4 py-10'>
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </div>
</section>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<section class="mb-40 overflow-hidden bg-gray-50">
  <!-- Navbar -->
  <!-- Navbar -->
  <!-- Background image -->
  <div class="relative h-[500px] category" style="background-image: url('<%= @category.image_url %>'); background-size: cover; background-position: center;">
    <div
      class="absolute top-0 right-0 bottom-0 left-0 h-full w-full overflow-hidden bg-fixed">
      <div class="flex h-full items-center justify-center">
        <div class="px-6 text-center text-white md:px-12">
          <h1 class="mt-6 font-serif mb-16 text-5xl  md:text-6xl xl:text-7xl tracking-widest">
            <%= @category.name %>
          </h1>
          <%= link_to 'Back', categories_path, class:"mb-2 inline-block rounded-full border-2 border-neutral-50 px-[46px] pt-[14px] pb-[12px] text-sm font-medium uppercase leading-normal text-neutral-50 transition duration-150 ease-in-out hover:border-neutral-100 hover:bg-neutral-500 hover:bg-opacity-10 hover:text-neutral-100 focus:border-neutral-100 focus:text-neutral-100 focus:outline-none focus:ring-0 active:border-neutral-200 active:text-neutral-200 md:mr-2 md:mb-0" %>
        </div>
      </div>
    </div>
  </div>
  <div
    class="-mt-2.5 text-white dark:text-neutral-800 md:-mt-4 lg:-mt-6 xl:-mt-10 h-[50px] scale-[2] origin-[top_center]">
    <svg viewBox="0 0 2880 48" xmlns="http://www.w3.org/2000/svg">
      <path d="M 0 48 L 1437.5 48 L 2880 48 L 2880 0 L 2160 0 C 1453.324 60.118 726.013 4.51 720 0 L 0 0 L 0 48 Z"
        fill="currentColor"></path>
    </svg>
  </div>
  <!-- Background image -->
</section>
<section  class='flex flex-col justify-center items-center'>
  <% if current_user.admin? %>
    <div class='flex'>
      <%= link_to "Edit this Category", edit_category_path(@category), class:"text-textColor mb-11 shadow-lg dark:shadow-lg  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button" %>
      <%= button_to "Destroy this category", @category,class:"text-textColor mb-11 shadow-lg dark:shadow-lg  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 button", method: :delete %>
    </div>
  <% end %>
  <%= render 'books/books' %>
</section>