config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :borrowings
  resources :books
  resources :categories
  resources :available_books
  devise_for :users
  root 'home#index'
  get 'borrow', to: 'home#borrow'
  get 'reserve', to: 'home#reserve'
  resources :users, only: %i[index destroy]
end

app/views/layouts/_alert.html.erb
<div id="alert-3" class="flex items-center justify-center  p-4 text-green-800  alert-bg dark:bg-gray-800 dark:text-green-400" role="alert">
  <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
  </svg>
  <span class="sr-only">Info</span>
  <div class="ml-3 text-sm  font-sana">
    <% if user_signed_in? %>
      <%= "Welcome #{current_user.username}!  You have #{notice}" %>
    <% else %>
      <%= "You have  #{notice}" %>
    <% end %>
  </div>
  <button type="button" class="ml-auto -mx-1.5 -my-1.5  text-green-500 rounded-lg focus:ring-2 f p-1.5 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-green-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-3" aria-label="Close">
    <span class="sr-only">Close</span>
    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
    </svg>
  </button>
</div>

app/views/layouts/_alertreg.html.erb
<div class="flex p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
  <svg class="flex-shrink-0 inline w-4 h-4 mr-3 mt-[2px]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
  </svg>
  <span class="sr-only">Info</span>
  <div>
    <span class="font-medium">Ensure that these requirements are met:</span>
    <ul class="mt-1.5 ml-4 list-disc list-inside">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class='flex justify-center sticky top-0 bg bg-white z-10'>
  <nav class="container bg-white border-gray-200  ">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <div class=" flex items-center">
        <%= image_tag('book.png', class:'h-10 mr-3', alt:"logo") %>
        <span class='font-serif font-semibold text-lg text-textColor mt-1' >ShelfWise</span>
      </div>
      <div class="flex items-center md:order-2">
        <% if user_signed_in? %>
          <button type="button" class="flex mr-3 text-sm rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
            <span class="sr-only">Open user menu</span>
            <%= image_tag('profile.png',class:'w-8 h-8 rounded-full', alt:"user photo") %>
          </button>
        <% else %>
          <%= link_to 'Sign In' , new_user_session_path, class:'mr-3' %>
        <% end %>
        <!-- Dropdown menu -->
        <% if user_signed_in? %>
          <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
            <div class="px-4 py-3">
              <span class="block text-sm text-gray-900 dark:text-white"><%= current_user.username %></span>
              <span class="block text-sm  text-gray-500 truncate dark:text-gray-400"><%= current_user.email %></span>
            </div>
            <ul class="py-2" aria-labelledby="user-menu-button">
              <li>
                <%= link_to 'My books' , borrowings_path,class:"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"  %>
              </li>
              <li>
                <%= link_to 'My Reservations' , reservations_path,class:"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"  %>
              </li>
              <li>
                <%= link_to 'Settings' , edit_user_registration_path,class:"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"  %>
              </li>
              <li>
                <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"block text-left px-4 w-full py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
              </li>
            </ul>
          </div>
        <% end %>
        <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
        </button>
      </div>
      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
        <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white ">
          <li>
            <%= link_to 'All Books', books_path , class:'block font-san-serif  py-2 pl-3 pr-4 text-textColor  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500' %>
          </li>
          <li>
            <%= link_to 'Available books', available_books_path , class:'block font-sans  py-2 pl-3 pr-4 text-textColor  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500' %>
          </li>
          <li>
            <%= link_to 'Categories', categories_path , class:'block font-sans  py-2 pl-3 pr-4 text-textColor  rounded md:bg-transparent  md:p-0 md:dark:text-blue-500' %>
          </li>
          <li>
            <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown" class="text-textColor flex items-center font-sans  py-2 pl-3 pr-4   rounded md:bg-transparent  md:p-0 md:dark:text-blue-500  " type="button">Our policies<svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
              </svg></button>
            <!-- Dropdown menu -->
            <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
              <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
                <li>
                  <%= link_to 'Borrowing', borrow_path, class:"block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
                </li>
                <li>
                  <%= link_to 'Reservation', reserve_path, class:"block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
                </li>
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <link
      rel="stylesheet"
      href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
    />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind",  "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class=" bg-gray-50">
      <%= render 'layouts/navigation'%>
      <% if notice %>
        <%= render 'layouts/alert' %>
      <% end %>
      <%= yield %>
    </main>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.turbo.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
  </body>
</html>